local errtest = io.popen("farts", 'r')
errtest:read("*a")
print(errtest:close())
errtest = io.popen("dir", 'r')
errtest:read("*a")
local ok, exit, code = errtest:close()
print(ok)
print(exit)
print(code)